### ISSUE TITLE
Pandas-ta doesnt work with numpy 2.0

### ISSUE THREAD

**Issue by Chuck321123** [twopirllc/pandas-ta#799]
So pandas-ta doesnt work with the newest numpy 2.0. 

Reproducible example:
```import pandas_ta as ta```

Log:
```
ImportError: cannot import name 'NaN' from 'numpy' (C:\Users\User\anaconda3\envs\py312Test\Lib\site-packages\numpy\__init__.py)
```
Would be nice to get support for the latest numpy version.

Pandas-ta version 0.3.14b
Python: 3.12.2

**Comment by twopirllc** [comment]
> So pandas-ta doesnt work with the newest numpy 2.0.

That's crazy @Chuck321123!   How is that possible?  🤷🏼‍♂️ 
It was released.... yesterday! 😮 

Please inform the following packages that they are not up to date with the newest _numpy 2.0_. I don't want them to miss out on the action.

<img width="820" alt="Screenshot 2024-06-17 at 12 13 35 PM" src="https://github.com/twopirllc/pandas-ta/assets/18198392/df73773e-3451-42e4-b613-2f41d3bd4df9">

**Note:** _streamlit_ is not necessary for *pandas-ta*

> Would be nice to get support for the latest numpy version.

Let's do it! ✅ 
Fork the repo, checkout the _development_ branch, edit (including tests), and submit a PR. 😎 

FYI, I'm now running:
Python: 3.11.9 & 3.12.4, no longer supporting <=3.9
Pandas TA  (_development_) 0.4.17b

**Comment by Chuck321123** [comment]
@twopirllc Unfortunately, I don't know how to do that. However, If anyone knows how to do it I would be very happy

**Comment by XotEmBotZ** [comment]
I have created the pull request. Have tested with server so it should work. Though haven't touched the package requirements though should also be compatible with 1.22. 
Kindly check

**Comment by danielverissimo** [comment]
Until the next release, on momentum/squeeze_pro.py change:

from numpy import NaN as npNaN

to 

import numpy as np

**Comment by twopirllc** [comment]
Import the whole _numpy_ namespace for a single item? 🤔

**Comment by danielverissimo** [comment]
Temporary bro, just to wait the final fiz release.

**Comment by seraph-wing** [comment]
instead, just rename to 

`from numpy import nan as npNaN`

**Comment by XotEmBotZ** [comment]
I believe this has already been done, the NaN is already renamed to nan and in the #801 I have fixed the imports regarding infinity (to inf). Let all these get merged then we can close this issue i guess.

**Comment by ironhak** [comment]
> Temporary bro, just to wait the final fix release.

Sorry but there are no new releases since 2021, why should a new release come out any soon?

**Comment by danielverissimo** [comment]
I don't know, the comment was just try to help, feel free to improve and send another one. This is not a PR.

**Comment by twopirllc** [comment]
> Sorry but there are no new releases since 2021, why should a new release come out any soon?

You shouldn't expect a _main_ release soon as the [development](https://github.com/twopirllc/pandas-ta/tree/development) (wih 360+ commits beyond _main_) is still ironing out _main_'s issues of numerous bugs, new indicators, speed and documentation improvements. If you want to help speed up this process, contributions to _developement_ or answering basic Issues have always been welcome. 😎 

However if you are as busy as I am, perhaps consider [Buying Me a Coffee](https://www.buymeacoffee.com/twopirllc) or [Sponsoring](https://github.com/twopirllc) my work instead. While it is Open Source, it is **not** free. I find it rather disheartening that **only** 25 people out of 4900 ⭐'s  (or 0.5% of people/companies/downstream projects have bought a ☕ and one is a sponsor). 🤷🏼‍♂️ 

Kind Regards!

**Comment by XotEmBotZ** [comment]
Was going to the log files of the server, noticed that the current version of pandas_ta asks for numpy>=1.26 which is a problem as numpy2 (latest) one is not supported in the main version. This is resulting in an error while trying to install pandas_ta. 
Though since it can be mitigated with replacing numpy2 with  numpy1.26, it gives the message that this project is abandoned and dosent work. 
Thus I kindly request that the numpy version should fixed to 1.26.4. thus preventing further confusion and errors.

**Comment by ironhak** [comment]
> > Sorry but there are no new releases since 2021, why should a new release come out any soon?
> 
> You shouldn't expect a _main_ release soon as the [development](https://github.com/twopirllc/pandas-ta/tree/development) (wih 360+ commits beyond _main_) is still ironing out _main_'s issues of numerous bugs, new indicators, speed and documentation improvements. If you want to help speed up this process, contributions to _developement_ or answering basic Issues have always been welcome. 😎
> 
> However if you are as busy as I am, perhaps consider [Buying Me a Coffee](https://www.buymeacoffee.com/twopirllc) or [Sponsoring](https://github.com/twopirllc) my work instead. While it is Open Source, it is **not** free. I find it rather disheartening that **only** 25 people out of 4900 ⭐'s (or 0.5% of people/companies/downstream projects have bought a ☕ and one is a sponsor). 🤷🏼‍♂️
> 
> Kind Regards!

Sorry, I thought this was discontinued. 

Also, I'm sorry there are not many donations but you're not pushing a new version since 2021, naturally end users will avoid a project that looks like discontinued, and less users = less donations. You can't complain about users not donating when they're not receiving an update since 2021, since there's also TA-Lib which is more active.

**Comment by kolyarice** [comment]
I went ahead and manually updated the import as suggested by @seraph-wing

The import succeeded but when using RSI another compat issue arose:
`_ = df.ta.rsi(cumulative=True, append=True)`
resulted in the error:

```
File ~/code/pylibs/lib/python3.12/site-packages/pandas_ta/core.py:1058, in AnalysisIndicators.rsi(self, length, scalar, drift, offset, **kwargs)
   1056 def rsi(self, length=None, scalar=None, drift=None, offset=None, **kwargs):
   1057     close = self._get_column(kwargs.pop("close", "close"))
-> 1058     result = rsi(close=close, length=length, scalar=scalar, drift=drift, offset=offset, **kwargs)
   1059     return self._post_process(result, **kwargs)

File ~/code/pylibs/lib/python3.12/site-packages/pandas_ta/momentum/rsi.py:22, in rsi(close, length, scalar, talib, drift, offset, **kwargs)
     20 # Calculate Result
     21 if Imports["talib"] and mode_tal:
---> 22     from talib import RSI
     23     rsi = RSI(close, length)
     24 else:

File ~/code/pylibs/lib/python3.12/site-packages/talib/__init__.py:93
     89 else:
     90     _wrapper = lambda x: x
---> 93 from ._ta_lib import (
     94     _ta_initialize, _ta_shutdown, MA_Type, __ta_version__,
     95     _ta_set_unstable_period as set_unstable_period,
     96     _ta_get_unstable_period as get_unstable_period,
     97     _ta_set_compatibility as set_compatibility,
     98     _ta_get_compatibility as get_compatibility,
     99     __TA_FUNCTION_NAMES__
    100 )
    102 # import all the func and stream functions
    103 from ._ta_lib import *

File talib/_ta_lib.pyx:1, in init talib._ta_lib()

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

**Comment by XotEmBotZ** [comment]
> I went ahead and manually updated the import as suggested by @seraph-wing
> 
> The import succeeded but when using RSI another compat issue arose: `_ = df.ta.rsi(cumulative=True, append=True)` resulted in the error:
> 
> ```
> File ~/code/pylibs/lib/python3.12/site-packages/pandas_ta/core.py:1058, in AnalysisIndicators.rsi(self, length, scalar, drift, offset, **kwargs)
>    1056 def rsi(self, length=None, scalar=None, drift=None, offset=None, **kwargs):
>    1057     close = self._get_column(kwargs.pop("close", "close"))
> -> 1058     result = rsi(close=close, length=length, scalar=scalar, drift=drift, offset=offset, **kwargs)
>    1059     return self._post_process(result, **kwargs)
> 
> File ~/code/pylibs/lib/python3.12/site-packages/pandas_ta/momentum/rsi.py:22, in rsi(close, length, scalar, talib, drift, offset, **kwargs)
>      20 # Calculate Result
>      21 if Imports["talib"] and mode_tal:
> ---> 22     from talib import RSI
>      23     rsi = RSI(close, length)
>      24 else:
> 
> File ~/code/pylibs/lib/python3.12/site-packages/talib/__init__.py:93
>      89 else:
>      90     _wrapper = lambda x: x
> ---> 93 from ._ta_lib import (
>      94     _ta_initialize, _ta_shutdown, MA_Type, __ta_version__,
>      95     _ta_set_unstable_period as set_unstable_period,
>      96     _ta_get_unstable_period as get_unstable_period,
>      97     _ta_set_compatibility as set_compatibility,
>      98     _ta_get_compatibility as get_compatibility,
>      99     __TA_FUNCTION_NAMES__
>     100 )
>     102 # import all the func and stream functions
>     103 from ._ta_lib import *
> 
> File talib/_ta_lib.pyx:1, in init talib._ta_lib()
> 
> ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
> ```

if we are talking about the current main branch, why not just limit the numpy to 1.26.4 in the setup.py. 
I guess this solves almost all issues. since no numpy 2 no numpy errors. 
In my opinion that is the most logical change that can be done without incurring the huge burden of dev in main branch. should just be few lines of code insead of many hours of debugging
please inform me if I am wrong

**Comment by twopirllc** [comment]
> Sorry, I thought this was discontinued. Also, I'm sorry there are not many donations but you're not pushing a new version since 2021, naturally end users will avoid a project that looks like discontinued, and less users = less donations. You can't complain about users not donating when they're not receiving an update since 2021, since there's also TA-Lib which is more active.

Understandable. This is not a high churn library nor is it archived (which is considered discontinued).

Thanks for the feedback

**Comment by twopirllc** [comment]
> In my opinion that is the most logical change that can be done without incurring the huge burden of dev in main branch. should just be few lines of code insead of many hours of debugging

Even better, let **not** upgrade prematurely to a new release especially when downstream library and applications haven't done so either... ie _pandas_, _pyarrow_, & _numba_., as _numpy_ states. 😅

<img width="615" alt="Screenshot 2024-06-18 at 1 31 58 PM" src="https://github.com/twopirllc/pandas-ta/assets/18198392/5173f3b3-6f76-4e74-b7c0-5584e3a3c077">

and 

<img width="830" alt="Screenshot 2024-06-18 at 1 32 52 PM" src="https://github.com/twopirllc/pandas-ta/assets/18198392/ba55f1c0-a780-42c3-aaea-720b6c540398">

<br>

Using ```pip``` to manage dependencies is the easiest solution if **right now** is _crucial_. In the mean time, with @XotEmBotZ's help 😎 , a future _development_ version will support this **urgent demand** for _numpy_ >= 2.

**Comment by XotEmBotZ** [comment]
> > In my opinion that is the most logical change that can be done without incurring the huge burden of dev in main branch. should just be few lines of code insead of many hours of debugging
> 
> Even better, let **not** upgrade prematurely to a new release especially when downstream library and applications haven't done so either... ie _pandas_, _pyarrow_, & _numba_., as _numpy_ states. 😅
> 
> <img alt="Screenshot 2024-06-18 at 1 31 58 PM" width="615" src="https://private-user-images.githubusercontent.com/18198392/342089506-5173f3b3-6f76-4e74-b7c0-5584e3a3c077.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNjQxMDIsIm5iZiI6MTcxOTE2MzgwMiwicGF0aCI6Ii8xODE5ODM5Mi8zNDIwODk1MDYtNTE3M2YzYjMtNmY3Ni00ZTc0LWI3YzAtNTU4NGUzYTNjMDc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDE3MzAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3YTliOWM2NDhhZGFlYWYzNWNjYTc3NTg3NjI5MjcyZmIxYTJmMjJhMTZhYjliZmVhMzI0ZDQ0NDNlMDQzNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BY6WXt7XTJih67AuGcJ5L8Ro4VSmhbfQLuJRPKIFrj0">
> and
> 
> <img alt="Screenshot 2024-06-18 at 1 32 52 PM" width="830" src="https://private-user-images.githubusercontent.com/18198392/342089635-ba55f1c0-a780-42c3-aaea-720b6c540398.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNjQxMDIsIm5iZiI6MTcxOTE2MzgwMiwicGF0aCI6Ii8xODE5ODM5Mi8zNDIwODk2MzUtYmE1NWYxYzAtYTc4MC00MmMzLWFhZWEtNzIwYjZjNTQwMzk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDE3MzAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMDk5MGI3MTUwMDQ4MTk5ZDE3MWFiMTljMTQwYjRjYjdjMGZlNTc0YjgzMTRhMDUzYTk1NzFkZDM1ZDQxN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QcvNubJNKk6kcLPmlqro3Ed9u6fCIyUN7FKcoZOacVw">
> Using `pip` to manage dependencies is the easiest solution if **right now** is _crucial_. In the mean time, with @XotEmBotZ's help 😎 , a future _development_ version will support this **urgent demand** for _numpy_ >= 2.

Yup, that's what I suggested in the last comment. In the mean time lets change the requirements mentioned in setpu.py to `numpy==1.26.4`  from `numpy>=1.26.4` thus preventing pip from installing numpy2 when installing pandas_ta

**Comment by XotEmBotZ** [comment]
> > > In my opinion that is the most logical change that can be done without incurring the huge burden of dev in main branch. should just be few lines of code insead of many hours of debugging
> > 
> > 
> > Even better, let **not** upgrade prematurely to a new release especially when downstream library and applications haven't done so either... ie _pandas_, _pyarrow_, & _numba_., as _numpy_ states. 😅
> > <img alt="Screenshot 2024-06-18 at 1 31 58 PM" width="615" src="https://private-user-images.githubusercontent.com/18198392/342089506-5173f3b3-6f76-4e74-b7c0-5584e3a3c077.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNjQxMDIsIm5iZiI6MTcxOTE2MzgwMiwicGF0aCI6Ii8xODE5ODM5Mi8zNDIwODk1MDYtNTE3M2YzYjMtNmY3Ni00ZTc0LWI3YzAtNTU4NGUzYTNjMDc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDE3MzAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3YTliOWM2NDhhZGFlYWYzNWNjYTc3NTg3NjI5MjcyZmIxYTJmMjJhMTZhYjliZmVhMzI0ZDQ0NDNlMDQzNjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BY6WXt7XTJih67AuGcJ5L8Ro4VSmhbfQLuJRPKIFrj0">
> > and
> > <img alt="Screenshot 2024-06-18 at 1 32 52 PM" width="830" src="https://private-user-images.githubusercontent.com/18198392/342089635-ba55f1c0-a780-42c3-aaea-720b6c540398.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNjQxMDIsIm5iZiI6MTcxOTE2MzgwMiwicGF0aCI6Ii8xODE5ODM5Mi8zNDIwODk2MzUtYmE1NWYxYzAtYTc4MC00MmMzLWFhZWEtNzIwYjZjNTQwMzk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDE3MzAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMDk5MGI3MTUwMDQ4MTk5ZDE3MWFiMTljMTQwYjRjYjdjMGZlNTc0YjgzMTRhMDUzYTk1NzFkZDM1ZDQxN2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QcvNubJNKk6kcLPmlqro3Ed9u6fCIyUN7FKcoZOacVw">
> > Using `pip` to manage dependencies is the easiest solution if **right now** is _crucial_. In the mean time, with @XotEmBotZ's help 😎 , a future _development_ version will support this **urgent demand** for _numpy_ >= 2.
> 
> Yup, that's what I suggested in the last comment. In the mean time lets change the requirements mentioned in setpu.py to `numpy==1.26.4` from `numpy>=1.26.4` thus preventing pip from installing numpy2 when installing pandas_ta. Should be a 2 or 3 lines of change so opening PR is just a time waste for you. you can just change `>` to `=` to make it work

since this is relatively small change ,by which date can we expect to get the update pushed to main branch?

**Comment by twopirllc** [comment]
Fixed _numpy_ version to 1.26.4 in _setup.py_ for _main_. Not updating pip for a single change.

**Comment by ironhak** [comment]
> Fixed _numpy_ version to 1.26.4 in _setup.py_ for _main_. Not updating pip for a single change.

Why not? It's stalled since 2021...

**Comment by eervin123** [comment]
> > Sorry but there are no new releases since 2021, why should a new release come out any soon?
> 
> You shouldn't expect a _main_ release soon as the [development](https://github.com/twopirllc/pandas-ta/tree/development) (wih 360+ commits beyond _main_) is still ironing out _main_'s issues of numerous bugs, new indicators, speed and documentation improvements. If you want to help speed up this process, contributions to _developement_ or answering basic Issues have always been welcome. 😎
> 
> However if you are as busy as I am, perhaps consider [Buying Me a Coffee](https://www.buymeacoffee.com/twopirllc) or [Sponsoring](https://github.com/twopirllc) my work instead. While it is Open Source, it is **not** free. I find it rather disheartening that **only** 25 people out of 4900 ⭐'s (or 0.5% of people/companies/downstream projects have bought a ☕ and one is a sponsor). 🤷🏼‍♂️
> 
> Kind Regards!

@twopirllc Thank you for all you do. I went to sponsor you just now and forgot I already was (not much but a small show of gratitude.) Come on folks let's help this fella retire early so he can build more cool Sh%^ for us.

**Comment by seraph-wing** [comment]
```
Using cached tzlocal-5.2-py3-none-any.whl (17 kB)
Installing collected packages: widgetsnbextension, tzlocal, tqdm, threadpoolctl, schedule, regex, numpy, mypy-extensions, llvmlite, jupyterlab-widgets, joblib, dill, scipy, numba, imageio, dateparser, scikit-learn, ipywidgets, vectorbt
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\vishw\AppData\Local\Temp\pip-uninstall-f04ies4l'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\vishw\.conda\envs\crypto-bot\Lib\site-packages\~umpy.libs'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\vishw\.conda\envs\crypto-bot\Lib\site-packages\numpy\~ft'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\vishw\.conda\envs\crypto-bot\Lib\site-packages\numpy\~inalg'.
  You can safely remove it manually.
  WARNING: Failed to remove contents in a temporary directory 'C:\Users\vishw\.conda\envs\crypto-bot\Lib\site-packages\numpy\~andom'.
  You can safely remove it manually.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pandas-ta 0.3.14b0 requires numpy==1.26.4, but you have numpy 1.23.5 which is incompatible.
Successfully installed dateparser-1.2.0 dill-0.3.8 imageio-2.34.2 ipywidgets-8.1.3 joblib-1.4.2 jupyterlab-widgets-3.0.11 llvmlite-0.39.1 mypy-extensions-1.0.0 numba-0.56.4 numpy-1.23.5 regex-2024.5.15 schedule-1.2.2 scikit-learn-1.5.0 scipy-1.13.1 threadpoolctl-3.5.0 tqdm-4.66.4 tzlocal-5.2 vectorbt-0.26.1 widgetsnbextension-4.0.11

```
this change resulted in above message when i installed vectorbt. I'm not sure whether to raaise this on the vectorbt repo, or here, since a large part of the people using pandas-ta would be using **vectorbt**. As @twopirllc mentioned, it might be best to keep the numpy version as '''numpy<2''' after all...

**Comment by twopirllc** [comment]
> Why not? It's stalled since 2021...

Yes, **only** the _main_ branch has been on hold.

> "This is **not** because it is dead, but rather because it is (mostly) right: the basic idea is right, and the implementation at least right enough.
> 
> This means there will not be constant activity and churn on the project, but rather a stewardship relationship: the main goal now is to not screw it up. The documentation will be improved, tests will be added, features/indicators will be added/removed as needed, but there will be no massive rewrite or constant updating. This is in contrast with the software industry in general and the front end world in particular, which often has comical levels of churn."
- Adapted from Intercooler JS

Unfortunately, the _development_ version still has more improvements left before merging into _main_. These improvements have been discussed recently in Issue #771 and below is the updated requirements from the post that @Rossco8 has helped with.

### Required Improvements
- Numpy/Numba implementations of core moving averages, especially loop based indicators
- Rewrite [slow indicators](https://github.com/twopirllc/pandas-ta/blob/development/examples/Speed_Test.ipynb) like **qqe**, **alligator**, etc...
- Complete remaining Hilbert Transform indicators from TA Lib
- Clean up or make new _examples_
- Necessary PRs

**Main Branch:** ```pip install git+https://github.com/twopirllc/pandas-ta```
**Dev Branch:** ```pip install -U git+https://github.com/twopirllc/pandas-ta.git@development```

If neither work for you, _fork_ and carry on or use another library.

🍀

**Comment by twopirllc** [comment]
> @twopirllc Thank you for all you do. I went to sponsor you just now and forgot I already was (not much but a small show of gratitude.) Come on folks let's help this fella retire early so he can build more cool Sh%^ for us.

@eervin123: Thank you for the recent sponsorship upgrade and continued support! It means a lot. 😎

**Comment by sbg0099** [comment]
> Until the next release, on momentum/squeeze_pro.py change:
> 
> `from numpy import NaN as npNaN`
> 
> to
> 
> `import numpy as np`

Hi all, I am just at the very beginning of working with python. So please forgive the dumb questions. Where is the renaming done at? I tried just using that in the IDE but I am still getting the same error. 

I still get 'ImportError: cannot import name 'NaN' from 'numpy'

**Comment by Royd12386** [comment]
Anyone has already a fix to this?

**Comment by bersoare** [comment]
for the folks that get here and dont read through all the comments, the import error can be fixed by installing numpy 1.26.4
`python3 -m pip install numpy==1.26.4 `

**Comment by amitbuch** [comment]
We are back to the Same issue with latest pandas-ta build 2024.1 and numpy 2.0.1. Can anyone help keep these dependencies lined up properly or open source mean open headaches for developers ?

**Comment by HyperionZhou** [comment]
Meet the same issue. Please fix it! Thank you very much!

**Comment by J-danger** [comment]
> for the folks that get here and dont read through all the comments, the import error can be fixed by installing numpy 1.26.4 `python3 -m pip install numpy==1.26.4 `

Thank you

**Comment by feiyuehchen** [comment]
> instead, just rename to
> 
> `from numpy import nan as npNaN`

This works for me. 
The error occurred in `pandas_ta/momentum/squeeze_pro.py`, line 2

**Comment by jrosebr1** [comment]
Hi all, happy to help however I can. It looks like this issue has been fixed since June in the development branch. What can I do to help get this over the finish line? I assume there is more work to be done in the development branch before it is merged in.

**Comment by dutchy54321** [comment]
but the issue is that with Python 3.9 and higher you need Numpy 2.0. Or I am using 3.12.5 and other libs need Numpy 2 or higher

**Comment by amitbuch** [comment]
downgrade numpy to 1.56 it worked for me after that.

**Comment by dutchy54321** [comment]
I need Numpy version 2.0 or higher so that solution will not work for me. I use Python 3.12.5, Numpy 2.1.1 because I use another plugin that needs Numpy 2 or higher

**Comment by grzesir** [comment]
Since this library does not seem to be in development anymore i have created a fork that works with numpy 2. See it here: https://github.com/grzesir/pandas-ta-numpy-2

**Comment by grzesir** [comment]
Here's an example of using the fixed numpy 2 version in a requirements.txt

lumibot>=3.8.6
git+https://github.com/grzesir/pandas-ta-numpy-2.git@main#egg=pandas-ta
alpaca_trade_api

**Comment by Zettt** [comment]
@grzesir I believe you can also submit a pull request.

**Comment by grzesir** [comment]
There is already a pull request for this months ago

Robert Grzesik 347-635-3416

**Comment by dmike23** [comment]
> Until the next release, on momentum/squeeze_pro.py change:
> 
> `from numpy import NaN as npNaN`
> 
> to
> 
> `import numpy as np`

so upon replacing you do not include "from pandas" ? or am i misunderstanding? 

thanks

**Comment by darshan-jain** [comment]
> Until the next release, on momentum/squeeze_pro.py change:
> 
> `from numpy import NaN as npNaN`
> 
> to
> 
> `import numpy as np`

This worked for me when I tried to install and import pandas_ta

**Comment by shenzhuangzhi1** [comment]
I don't understand why the issue extends until 0.3.14

**Comment by grzesir** [comment]
Agreed. I think at this point it is poor development skills or just pure
neglect

Robert Grzesik

**Comment by okkesd** [comment]
Guys, just go to

lib/python3.11/site-packages/pandas_ta/momentum/squeeze_pro.py file and change the first import to this :

from numpy import nan as npNaN

it will be fine after that

**Comment by jrosebr1** [comment]
> it will be fine after that

Yes, 100% — if you're doing basic dev, that will _absolutely_ work.

The _problem_ is if you're using `pandas-ta` in a production build. You would need to freeze your NumPy to v1.x, which may or may not be possible, depending on your other package dependencies.

Another option is to have your build script update the `pandas-ta` code after install, but that can be fragile.

**Comment by AY21865** [comment]
> Guys, just go to
> 
> lib/python3.11/site-packages/pandas_ta/momentum/squeeze_pro.py file and change the first import to this :
> 
> from numpy import nan as npNaN
> 
> it will be fine after that

this resolve the issu thank you

**Comment by icemagno** [comment]
Still having this issue. When we will have a definitive solution?

**Comment by drew1two** [comment]
Here is gpt-3o-mini's idea for a fix:-
My approach would be twofold:

Patch the problematic import in pandas-ta. In the file "pandas_ta/momentum/squeeze_pro.py," change the line

from numpy import NaN as npNaN

to

from numpy import nan as npNaN
This small change allows pandas-ta to work with newer versions of numpy that no longer expose “NaN” (uppercase).

To avoid broader dependency conflicts (as you’ve seen with vectorbt and others), I would also control the numpy version used in your environment. In practice, this means pinning numpy to version 1.26.4 (or even to “numpy<2” if that is acceptable) via your environment’s dependency configuration or by editing the pandas-ta setup.py requirement from “numpy>=1.26.4” to “numpy==1.26.4.” This aligns with the GitHub discussions where maintainers opted for a strict version so that downstream users (especially those using pandas-ta in conjunction with vectorbt, pydantic, openai, dotenv, etc.) don’t run into binary incompatibilities.
This combined fix is minimal—just a couple of code changes—and it prevents pip (or mamba) from updating numpy beyond 1.26.4, which is the version that works reliably with pandas-ta as per the discussion you provided. It also avoids deeper debugging and the cascading compatibility issues seen with numpy 2.x.

This is the solution I’d recommend to resolve your issues.
