### PR TITLE
Fixed numpy import errors in development branch

### LINKED ISSUE #799: Pandas-ta doesnt work with numpy 2.0
So pandas-ta doesnt work with the newest numpy 2.0. 

Reproducible example:
```import pandas_ta as ta```

Log:
```
ImportError: cannot import name 'NaN' from 'numpy' (C:\Users\User\anaconda3\envs\py312Test\Lib\site-packages\numpy\__init__.py)
```
Would be nice to get support for the latest numpy version.

Pandas-ta version 0.3.14b
Python: 3.12.2

### PR DESCRIPTION
**Pull request by XotEmBotZ**
fixes #799 in dev branch

### CODE REVIEW

**Comment by twopirllc** [comment]
@XotEmBotZ,

Awesome! I will work it into the next push with #797.

Appreciate the help

**Comment by twopirllc** [comment]
@XotEmBotZ 

Sadly, _numpy_ 2.0 is still [breaking](https://github.com/twopirllc/pandas-ta/actions/runs/9767602960/job/26963236182) with TA Lib. Fixing to _numpy==1.26.4_ is the only solution for the time being.

I assume you do not have TA Lib installed, correct?

KJ

**Comment by twopirllc** [comment]
@XotEmBotZ 

TA Lib also has a numpy 2.x issue and seems to be pending Cython. 🤷🏼‍♂️  See [Support for Numpy 2.0](https://github.com/TA-Lib/ta-lib-python/issues/660) & [Numpy incompatible with Talib](https://github.com/TA-Lib/ta-lib-python/issues/661).
